/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calc;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.Arrays;

/**
 *
 * @author Alumno Tarde
 */
public class CalculadoraSwing extends javax.swing.JFrame {

    String valor1 = "";
    String valor2 = "";
    Boolean esDecimal = false;
    Boolean esDivision = false;
    Boolean esMultiplicacion = false;
    Boolean esSuma = false;
    Boolean esResta = false;
    Boolean resultado = false;
    String result = "";
    
        
    /**
     * Creates new form NewJFrame
     */
    public CalculadoraSwing() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto = new javax.swing.JTextField();
        memoriamas = new javax.swing.JButton();
        borrarTodo = new javax.swing.JButton();
        botonmas = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        botondividir = new javax.swing.JButton();
        botonmultiplicar = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();
        botonsiete = new javax.swing.JButton();
        botondos = new javax.swing.JButton();
        botonuno = new javax.swing.JButton();
        botonocho = new javax.swing.JButton();
        botonnueve = new javax.swing.JButton();
        botontres = new javax.swing.JButton();
        botonpunto = new javax.swing.JButton();
        botoncero = new javax.swing.JButton();
        botoncuatro = new javax.swing.JButton();
        botoncinco = new javax.swing.JButton();
        botonseis = new javax.swing.JButton();
        textoOperaciones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        texto.setBackground(new java.awt.Color(102, 102, 102));
        texto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        memoriamas.setBackground(new java.awt.Color(51, 51, 51));
        memoriamas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        memoriamas.setForeground(new java.awt.Color(255, 255, 255));
        memoriamas.setText("CE");
        memoriamas.setFocusable(false);
        memoriamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriamasActionPerformed(evt);
            }
        });
        memoriamas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memoriamasKeyPressed(evt);
            }
        });

        borrarTodo.setBackground(new java.awt.Color(51, 51, 51));
        borrarTodo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        borrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        borrarTodo.setText("C");
        borrarTodo.setFocusable(false);
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });

        botonmas.setBackground(new java.awt.Color(51, 51, 51));
        botonmas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonmas.setForeground(new java.awt.Color(255, 255, 255));
        botonmas.setText("+");
        botonmas.setFocusable(false);
        botonmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasActionPerformed(evt);
            }
        });

        botoneliminar.setBackground(new java.awt.Color(51, 51, 51));
        botoneliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botoneliminar.setForeground(new java.awt.Color(255, 255, 255));
        botoneliminar.setText("<----");
        botoneliminar.setFocusable(false);
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        botonmenos.setBackground(new java.awt.Color(51, 51, 51));
        botonmenos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonmenos.setForeground(new java.awt.Color(255, 255, 255));
        botonmenos.setText("-");
        botonmenos.setFocusable(false);
        botonmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmenosActionPerformed(evt);
            }
        });

        botondividir.setBackground(new java.awt.Color(51, 51, 51));
        botondividir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botondividir.setForeground(new java.awt.Color(255, 255, 255));
        botondividir.setText("/");
        botondividir.setFocusable(false);
        botondividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondividirActionPerformed(evt);
            }
        });

        botonmultiplicar.setBackground(new java.awt.Color(51, 51, 51));
        botonmultiplicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonmultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        botonmultiplicar.setText("*");
        botonmultiplicar.setFocusable(false);
        botonmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicarActionPerformed(evt);
            }
        });

        botonigual.setBackground(new java.awt.Color(51, 51, 51));
        botonigual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonigual.setForeground(new java.awt.Color(255, 255, 255));
        botonigual.setText("=");
        botonigual.setFocusable(false);
        botonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonigualActionPerformed(evt);
            }
        });

        botonsiete.setBackground(new java.awt.Color(102, 102, 102));
        botonsiete.setForeground(new java.awt.Color(255, 255, 255));
        botonsiete.setText("7");
        botonsiete.setFocusable(false);
        botonsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsieteActionPerformed(evt);
            }
        });

        botondos.setBackground(new java.awt.Color(102, 102, 102));
        botondos.setForeground(new java.awt.Color(255, 255, 255));
        botondos.setText("2");
        botondos.setFocusable(false);
        botondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondosActionPerformed(evt);
            }
        });

        botonuno.setBackground(new java.awt.Color(102, 102, 102));
        botonuno.setForeground(new java.awt.Color(255, 255, 255));
        botonuno.setText("1");
        botonuno.setFocusable(false);
        botonuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonunoActionPerformed(evt);
            }
        });

        botonocho.setBackground(new java.awt.Color(102, 102, 102));
        botonocho.setForeground(new java.awt.Color(255, 255, 255));
        botonocho.setText("8");
        botonocho.setFocusable(false);
        botonocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonochoActionPerformed(evt);
            }
        });

        botonnueve.setBackground(new java.awt.Color(102, 102, 102));
        botonnueve.setForeground(new java.awt.Color(255, 255, 255));
        botonnueve.setText("9");
        botonnueve.setFocusable(false);
        botonnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnueveActionPerformed(evt);
            }
        });

        botontres.setBackground(new java.awt.Color(102, 102, 102));
        botontres.setForeground(new java.awt.Color(255, 255, 255));
        botontres.setText("3");
        botontres.setFocusable(false);
        botontres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botontresActionPerformed(evt);
            }
        });

        botonpunto.setBackground(new java.awt.Color(102, 102, 102));
        botonpunto.setForeground(new java.awt.Color(255, 255, 255));
        botonpunto.setText(".");
        botonpunto.setFocusable(false);
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });

        botoncero.setBackground(new java.awt.Color(102, 102, 102));
        botoncero.setForeground(new java.awt.Color(255, 255, 255));
        botoncero.setText("0");
        botoncero.setBorder(null);
        botoncero.setBorderPainted(false);
        botoncero.setFocusable(false);
        botoncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonceroActionPerformed(evt);
            }
        });
        botoncero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonceroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonceroKeyTyped(evt);
            }
        });

        botoncuatro.setBackground(new java.awt.Color(102, 102, 102));
        botoncuatro.setForeground(new java.awt.Color(255, 255, 255));
        botoncuatro.setText("4");
        botoncuatro.setFocusable(false);
        botoncuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncuatroActionPerformed(evt);
            }
        });

        botoncinco.setBackground(new java.awt.Color(102, 102, 102));
        botoncinco.setForeground(new java.awt.Color(255, 255, 255));
        botoncinco.setText("5");
        botoncinco.setFocusable(false);
        botoncinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncincoActionPerformed(evt);
            }
        });

        botonseis.setBackground(new java.awt.Color(102, 102, 102));
        botonseis.setForeground(new java.awt.Color(255, 255, 255));
        botonseis.setText("6");
        botonseis.setFocusable(false);
        botonseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseisActionPerformed(evt);
            }
        });

        textoOperaciones.setBackground(new java.awt.Color(102, 102, 102));
        textoOperaciones.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        textoOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        textoOperaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textoOperaciones.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botoncuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonsiete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(memoriamas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonuno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonocho, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botoneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(botonnueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botoncinco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botondos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botoncero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botontres, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(botonseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonpunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botondividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonmenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonmas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(botonmultiplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonigual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(textoOperaciones)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textoOperaciones)
                .addGap(3, 3, 3)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(memoriamas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botoneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonnueve, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonocho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonsiete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonseis, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(botoncinco, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(botoncuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botondividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botondos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botontres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonmultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonpunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoncero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseisActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("6");
        
    }//GEN-LAST:event_botonseisActionPerformed

    private void botoncincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncincoActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("5");
    }//GEN-LAST:event_botoncincoActionPerformed

    private void botoncuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncuatroActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("4");
    }//GEN-LAST:event_botoncuatroActionPerformed

    private void botonceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonceroActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("0");
    }//GEN-LAST:event_botonceroActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        else if(esDecimal==true){}
        else{
            pulsarNumero(".");
            esDecimal = true;
        }
    }//GEN-LAST:event_botonpuntoActionPerformed

    private void botontresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botontresActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("3");
    }//GEN-LAST:event_botontresActionPerformed

    private void botonnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnueveActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("9");
    }//GEN-LAST:event_botonnueveActionPerformed

    private void botonochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonochoActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("8");
    }//GEN-LAST:event_botonochoActionPerformed

    private void botonunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonunoActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("1");
    }//GEN-LAST:event_botonunoActionPerformed

    private void botondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondosActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("2");
    }//GEN-LAST:event_botondosActionPerformed

    private void botonsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsieteActionPerformed
        if(resultado==true){
            siguienteOperacion();
        }
        pulsarNumero("7");
    }//GEN-LAST:event_botonsieteActionPerformed

    private void botonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonigualActionPerformed
        valor2 = texto.getText();
        textoOperaciones.setText(textoOperaciones.getText()+valor2+" = ");
        if(esDivision == true){
            result = (String.valueOf(Float.valueOf(valor1)/Float.valueOf(valor2)));
            if((result.substring(result.length()-2,result.length())).equals(".0")){
                result = result.substring(0, result.length()-2);
                texto.setText(result);
            }
            else{texto.setText(result);}
            resultado = true;
        }
        else if(esMultiplicacion == true){
            result = (String.valueOf(Float.valueOf(valor1)*Float.valueOf(valor2)));
            if((result.substring(result.length()-2,result.length())).equals(".0")){
                result = result.substring(0, result.length()-2);
                texto.setText(result);
            }
            else{texto.setText(result);}            
            resultado = true;
        }
        else if(esSuma == true){
            result = (String.valueOf(Float.valueOf(valor1)+Float.valueOf(valor2)));
            if((result.substring(result.length()-2,result.length())).equals(".0")){
                result = result.substring(0, result.length()-2);
                texto.setText(result);
            }
            else{texto.setText(result);}            
            resultado = true;
        }
        else if(esResta == true){
            result = (String.valueOf(Float.valueOf(valor1)-Float.valueOf(valor2)));
            if((result.substring(result.length()-2,result.length())).equals(".0")){
                result = result.substring(0, result.length()-2);
                texto.setText(result);
            }
            else{texto.setText(result);}
            resultado = true;
        }
        else{
            texto.setText("ERRORRRRRRRRR!!!!");
        }
    }//GEN-LAST:event_botonigualActionPerformed

    private void botonmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicarActionPerformed
        resultado = false;
        valor1 = texto.getText();
        textoOperaciones.setText(valor1+" * ");
        texto.setText("");
        esMultiplicacion = true;
        esDecimal = false;
    }//GEN-LAST:event_botonmultiplicarActionPerformed

    private void botondividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondividirActionPerformed
        resultado = false;
        valor1 = texto.getText();
        textoOperaciones.setText(valor1+" / ");
        texto.setText("");
        esDivision = true;
        esDecimal = false;
    }//GEN-LAST:event_botondividirActionPerformed

    private void botonmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmenosActionPerformed
        resultado = false;
        valor1 = texto.getText();
        textoOperaciones.setText(valor1+" - ");
        texto.setText("");
        esResta = true;
        esDecimal = false;
    }//GEN-LAST:event_botonmenosActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        if(resultado == false){
        String borrar = texto.getText();
        texto.setText(borrar.substring(0, borrar.length()-1));
        }
        else if(texto.equals(null)){}
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void botonmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasActionPerformed
        resultado = false;
        valor1 = texto.getText();
        textoOperaciones.setText(valor1+" + ");
        texto.setText("");
        esSuma = true;
        esDecimal = false;
    }//GEN-LAST:event_botonmasActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        siguienteOperacion();
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void memoriamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriamasActionPerformed
        texto.setText("");
    }//GEN-LAST:event_memoriamasActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    private void memoriamasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoriamasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_memoriamasKeyPressed

    private void botonceroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonceroKeyTyped

    }//GEN-LAST:event_botonceroKeyTyped

    private void botonceroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonceroKeyPressed

    }//GEN-LAST:event_botonceroKeyPressed

;
    public void operacion() {

    }
    private void pulsarNumero(String args){
        texto.setText(texto.getText()+args);

    }
    private void siguienteOperacion(){
        texto.setText("");
        textoOperaciones.setText("");
        valor1 = "";
        valor2 = "";
        esDecimal = false;
        esMultiplicacion = false;
        esDivision = false;
        esSuma = false;
        esResta = false;
        resultado = false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton botoncero;
    private javax.swing.JButton botoncinco;
    private javax.swing.JButton botoncuatro;
    private javax.swing.JButton botondividir;
    private javax.swing.JButton botondos;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonigual;
    private javax.swing.JButton botonmas;
    private javax.swing.JButton botonmenos;
    private javax.swing.JButton botonmultiplicar;
    private javax.swing.JButton botonnueve;
    private javax.swing.JButton botonocho;
    private javax.swing.JButton botonpunto;
    private javax.swing.JButton botonseis;
    private javax.swing.JButton botonsiete;
    private javax.swing.JButton botontres;
    private javax.swing.JButton botonuno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton memoriamas;
    private javax.swing.JTextField texto;
    private javax.swing.JTextField textoOperaciones;
    // End of variables declaration//GEN-END:variables
}
